"use strict";
const { google } = require("googleapis");
const { getGoogleClient } = require("./auth-service");
const gmail = google.gmail("v1");

async function dropMyResumeViaGmailService(toEmailAddress = "veerareddy.obula@gmail.com") {
  getGoogleClient().then(async () => {
    const messageParts = [];
    messageParts.push(`From: vbreddy.obulareddy@gmail.com`);
    messageParts.push(`To: ${toEmailAddress}`);
    messageParts.push("Content-Type: text/html; charset=utf-8");
    messageParts.push("MIME-Version: 1.0");
    messageParts.push(`Subject: Javascript Full-Stack Developer`);
    messageParts.push("");
    messageParts.push("This is new Format Constructor");
    messageParts.push("So... <b>Hello VEERA!</b>  🤘❤️😎");
    messageParts.push("autogenerated email from : <a href='https://vbreddy.life'>vbreddy.life</a>");
    console.log("--==messageParts ", messageParts);
    const message = messageParts.join("\n");

    const encodedMessage = Buffer.from(message)
      .toString("base64")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");

    const res = await gmail.users.messages.send({
      userId: "me",
      requestBody: {
        raw: encodedMessage,
      },
    });
    console.log(res.data);
  });
}

module.exports = {
  dropMyResumeViaGmailService,
};
